# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

test:
  secret_key_base: 421e484d7998b071f8358d8197e4fee3fe23ee281525f3f060be79836d9b3def398ebc63d18bc1d36149f2e391693ab27bc1e9fd6a3e57c18c27669318beb56f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  CLIENT_ID:  <%= ENV['GH_BASIC_CLIENT_ID'] %>
  CLIENT_SECRET: <%= ENV['GH_BASIC_SECRET_ID'] %>
